### ISSUE TITLE
[BACK] Rota para retornar os livros com mais descontos

### ISSUE THREAD

**Issue by HendrickFS** [matheusa1/cafe-books-back#70]

**Comment by LuizAbudi** [comment]
![image](https://github.com/matheusa1/cafe-books-back/assets/84038960/bc3e72cf-15a4-4cc8-ad3e-e5dd23191ec4)

Está retornando os 10 primeiros livros, fazendo a conta para saber a devida porcentagem de cada um:

`[
	{
		"book": {
			"isbn": "1234567",
			"title": "Example Book",
			"publisher": "Example Publisher",
			"country": "brasil",
			"language": "English",
			"image": "https://example.com/path/to/book/cover.jpg",
			"description": "A sample description of the book.",
			"year": 2023,
			"pages": 300,
			"price": 19.99,
			"promotional_price": 9.99,
			"stock": 100,
			"sales": 0,
			"category": [
				"Fiction"
			],
			"author": []
		},
		"discount_percentage": "50%"
	},
	{
		"book": {
			"isbn": "12345678",
			"title": "Example Book",
			"publisher": "Example Publisher",
			"country": "brasil",
			"language": "English",
			"image": "https://example.com/path/to/book/cover.jpg",
			"description": "A sample description of the book.",
			"year": 2023,
			"pages": 300,
			"price": 19.99,
			"promotional_price": 9.99,
			"stock": 100,
			"sales": 0,
			"category": [
				"Fiction"
			],
			"author": [
				"Luiz"
			]
		},
		"discount_percentage": "50%"
	},
	{
		"book": {
			"isbn": "123456789",
			"title": "TEste Book",
			"publisher": "Example Publisher",
			"country": "brasil",
			"language": "English",
			"image": "https://example.com/path/to/book/cover.jpg",
			"description": "aaaa",
			"year": 2023,
			"pages": 3000,
			"price": 19.99,
			"promotional_price": 12.55,
			"stock": 100,
			"sales": 0,
			"category": [
				"Fiction"
			],
			"author": [
				"Luiz"
			]
		},
		"discount_percentage": "37%"
	},
	{
		"book": {
			"isbn": "123",
			"title": "123",
			"publisher": "123",
			"country": "123",
			"language": "123",
			"image": "123",
			"description": "123",
			"year": 123,
			"pages": 123,
			"price": 123.0,
			"promotional_price": 123.0,
			"stock": 115,
			"sales": 8,
			"category": [],
			"author": []
		},
		"discount_percentage": "0%"
	},
	{
		"book": {
			"isbn": "12345",
			"title": "1234",
			"publisher": "1234",
			"country": "1234",
			"language": "1234",
			"image": "1234",
			"description": "1234",
			"year": 1234,
			"pages": 1234,
			"price": 1234.0,
			"promotional_price": 1234.0,
			"stock": 1234,
			"sales": 0,
			"category": [],
			"author": []
		},
		"discount_percentage": "0%"
	}
]`
